/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "booking.h"

bool_t
xdr_slot (XDR *xdrs, slot *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->slot_id))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->available))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_booking_request (XDR *xdrs, booking_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->slot_id))
		 return FALSE;
	return TRUE;
}
