/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BOOKING_H_RPCGEN
#define _BOOKING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct slot {
	int slot_id;
	bool_t available;
};
typedef struct slot slot;

struct booking_request {
	int slot_id;
};
typedef struct booking_request booking_request;

#define BOOKING_PROG 0x20000002
#define BOOKING_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define BOOK_SLOT 1
extern  char ** book_slot_1(booking_request *, CLIENT *);
extern  char ** book_slot_1_svc(booking_request *, struct svc_req *);
#define GET_SLOT_STATUS 2
extern  slot * get_slot_status_1(int *, CLIENT *);
extern  slot * get_slot_status_1_svc(int *, struct svc_req *);
extern int booking_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BOOK_SLOT 1
extern  char ** book_slot_1();
extern  char ** book_slot_1_svc();
#define GET_SLOT_STATUS 2
extern  slot * get_slot_status_1();
extern  slot * get_slot_status_1_svc();
extern int booking_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_slot (XDR *, slot*);
extern  bool_t xdr_booking_request (XDR *, booking_request*);

#else /* K&R C */
extern bool_t xdr_slot ();
extern bool_t xdr_booking_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BOOKING_H_RPCGEN */
