/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FACT_H_RPCGEN
#define _FACT_H_RPCGEN

#include <tirpc/rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct num {
	int a;
};
typedef struct num num;

#define FACT_PRO 0x12345678
#define FACT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define fact 1
extern  int * fact_1(num *, CLIENT *);
extern  int * fact_1_svc(num *, struct svc_req *);
extern int fact_pro_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fact 1
extern  int * fact_1();
extern  int * fact_1_svc();
extern int fact_pro_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_num (XDR *, num*);

#else /* K&R C */
extern bool_t xdr_num ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FACT_H_RPCGEN */
