/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ODDEVEN_H_RPCGEN
#define _ODDEVEN_H_RPCGEN

#include <tirpc/rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct rpc {
	int arr[10];
};
typedef struct rpc rpc;

#define ODD_EVEN_PR 0x12345678
#define ODD_EVEN_V 1

#if defined(__STDC__) || defined(__cplusplus)
#define oddeven 1
extern  int * oddeven_1(rpc *, CLIENT *);
extern  int * oddeven_1_svc(rpc *, struct svc_req *);
extern int odd_even_pr_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define oddeven 1
extern  int * oddeven_1();
extern  int * oddeven_1_svc();
extern int odd_even_pr_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpc (XDR *, rpc*);

#else /* K&R C */
extern bool_t xdr_rpc ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ODDEVEN_H_RPCGEN */
